# Generated by Django 3.2.5 on 2022-04-21 22:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
